### ISSUE TITLE
Contacts related apps (phone, contacts, etc) crashes upon startup

### ISSUE THREAD

**Issue by mdamt** [ridon/ridon#1]
logcat:

```
E/DatabaseUtils( 1497): Writing exception to parcel
E/DatabaseUtils( 1497): java.lang.IllegalArgumentException: Invalid column account_type
E/DatabaseUtils( 1497):     at android.database.sqlite.SQLiteQueryBuilder.computeProjection(SQLiteQueryBuilder.java:632)
E/DatabaseUtils( 1497):     at android.database.sqlite.SQLiteQueryBuilder.buildQuery(SQLiteQueryBuilder.java:447)
E/DatabaseUtils( 1497):     at com.android.providers.contacts.ContactsProvider2.queryLocal(ContactsProvider2.java:5424)
E/DatabaseUtils( 1497):     at com.android.providers.contacts.ContactsProvider2.query(ContactsProvider2.java:5038)
E/DatabaseUtils( 1497):     at android.content.ContentProvider$Transport.query(ContentProvider.java:213)
E/DatabaseUtils( 1497):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
E/DatabaseUtils( 1497):     at android.os.Binder.execTransact(Binder.java:446)

```

**Comment by mdamt** [comment]
Fixed
