### ISSUE TITLE
Browser crashes upon startup

### ISSUE THREAD

**Issue by mdamt** [ridon/ridon#2]
```
D/AndroidRuntime( 6228): Shutting down VM
E/AndroidRuntime( 6228): FATAL EXCEPTION: main
E/AndroidRuntime( 6228): Process: com.android.browser, PID: 6228
E/AndroidRuntime( 6228): java.lang.RuntimeException: Unable to get provider com.android.browser.provider.SnapshotProvider: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime( 6228):    at android.app.ActivityThread.installProvider(ActivityThread.java:5002)
E/AndroidRuntime( 6228):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
E/AndroidRuntime( 6228):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
E/AndroidRuntime( 6228):    at android.app.ActivityThread.access$1600(ActivityThread.java:147)
E/AndroidRuntime( 6228):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
E/AndroidRuntime( 6228):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6228):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6228):    at android.app.ActivityThread.main(ActivityThread.java:5256)
E/AndroidRuntime( 6228):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6228):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6228):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime( 6228):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
E/AndroidRuntime( 6228): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime( 6228):    at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:1056)
E/AndroidRuntime( 6228):    at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:211)
E/AndroidRuntime( 6228):    at com.android.browser.provider.SnapshotProvider.getOldDatabasePath(SnapshotProvider.java:116)
E/AndroidRuntime( 6228):    at com.android.browser.provider.SnapshotProvider.migrateToDataFolder(SnapshotProvider.java:123)
E/AndroidRuntime( 6228):    at com.android.browser.provider.SnapshotProvider.onCreate(SnapshotProvider.java:137)
E/AndroidRuntime( 6228):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1720)
E/AndroidRuntime( 6228):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1689)
E/AndroidRuntime( 6228):    at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
E/AndroidRuntime( 6228):    ... 11 more
W/ActivityManager(  491):   Force finishing activity com.android.browser/.BrowserActivity
I/OpenGLRenderer(  491): Initialized EGL, version 1.4

```

**Comment by mdamt** [comment]
Happens when no sd card is present
